In [28]:
# https://medium.com/@erikhallstrm/hello-world-rnn-83cd7105b767
DEBUG = True

import re, random, math, csv, io, string, itertools, sys, functools,math
import numpy as np
# import pandas as pd
import tensorflow as tf

def test_data_1(n_unrollings=100, echo_step=2, batch_size=5):
    x = np.array(np.random.choice(2, n_unrollings, p=[0.5, 0.5]))
    y = np.roll(x, echo_step)
    y[0:echo_step] = 0

    x = x.reshape((batch_size, -1))  # The first index changing slowest, subseries as rows
    y = y.reshape((batch_size, -1))

    return (x, y)

class RNN:
    hp = dict(
        batch_sz=5,
        backprop_len=15,
        n_classes=2,
        state_sz=4,
        ckpt_path="./checkpoints/"
    )
    def __init__(self, **hyper_parameters):
        if hyper_parameters is not None:
            for k, v in hyper_parameters.items():
                self.hp[k] = v
    
    def _init_graph(self):
        tf.reset_default_graph()
        self.inputs_batch = tf.placeholder(tf.float32, [self.hp['batch_sz'], self.hp['backprop_len']], "inputs_batch")
        self.labels_batch = tf.placeholder(tf.int32,   [self.hp['batch_sz'], self.hp['backprop_len']],   "labels_batch")
        self.init_state = tf.placeholder(tf.float32,   [self.hp['batch_sz'], self.hp['state_sz']],     "init_state")
        
        self.w_tarns = tf.Variable(
            np.random.rand(
                self.hp['state_sz']+1, #prev_state + 1 for inputs
                self.hp['state_sz']
            ),
            dtype=tf.float32
        )
        self.b_trans = tf.Variable(np.zeros([1,self.hp['state_sz']]), dtype=tf.float32)
        self.w_out = tf.Variable(np.random.rand(self.hp["state_sz"], self.hp["n_classes"]), dtype=tf.float32)
        self.b_out = tf.Variable(np.zeros([1,self.hp['n_classes']]), dtype=tf.float32)
        
        self.inputs_seq = tf.unstack(self.inputs_batch, axis=1)
        self.labels_seq = tf.unstack(self.labels_batch, axis=1)

    def _forward(self):
        curr_state = self.init_state
        state_seq = []
        for curr_input in self.inputs_seq:
            curr_input = tf.reshape(curr_input, [self.hp['batch_sz'], 1])
            comm = tf.concat([curr_input, curr_state], axis=1)
            next_state = tf.tanh(tf.matmul(comm, self.w_tarns) + self.b_trans)
            state_seq.append(next_state)
            curr_state = next_state
            
        self.last_state = curr_state
        self.logits_seq = [tf.matmul(state, self.w_out)+self.b_out for state in state_seq]
        self.preds_seq = [tf.nn.softmax(logit) for logit in self.logits_seq]
        
    def _train_graph(self):
        self._init_graph()
        self._forward()
        
        # backward
        losses = [
            tf.nn.sparse_softmax_cross_entropy_with_logits(
                logits = logits,
                labels = labels
            ) 
            for logits, labels in zip(self.logits_seq, self.labels_seq)
        ]
        self.total_loss = tf.reduce_mean(losses)
        self.train_step = tf.train.AdagradOptimizer(0.3).minimize(self.total_loss)
        tf.summary.histogram(self.total_loss.op.name, self.total_loss)
        tf.summary.histogram(self.last_state.op.name, self.last_state)
        self.merged = tf.summary.merge_all()
    
    def _infer_graph(self):
        self._init_graph()
        self._forward()
        
        
    def predict(self, x):
        nobs = np.shape(x)[0]
        self._infer_graph()
        prediction=[]
        if nobs<self.hp["backprop_len"]:
            x = np.pad(x, (0, self.hp["backprop_len"] - nobs),mode="constant")
        with tf.Session() as sess:
            sess.run(tf.initialize_all_variables())
            ckpt = tf.train.get_checkpoint_state("checkpoints")
            n_batches = 1 + int(nobs>self.hp['backprop_len'])*(nobs - self.hp['backprop_len'])
            start_idx = 0
            end_idx = self.hp["backprop_len"]
            curr_state = np.zeros([1, self.hp['state_sz']])
            is_first = True
            for batch_num in range(n_batches):
                x_batch = [x[start_idx:]]
                pred = sess.run(
                    [self.preds_seq],
                    feed_dict={
                        self.inputs_batch:x_batch,
                        self.init_state:curr_state
                    }
                )
                if is_first:
                    prediction.extend(pred)
                    is_first=False
                else:
                    prediction.append(pred[-1])
        return prediction[0][:nobs]
    
    def train(self, x, y,n_epochs=10):
        nobs = len(x)
        divider = self.hp['batch_sz']*self.hp["backprop_len"]*n_epochs
        pad_len = divider - (nobs%divider)
        
        if nobs<pad_len:
            raise Exception("Wrong n_epochs({n_epochs}): choose smaller value.")
        x_batch=np.reshape(
            np.pad(x, (0, pad_len), mode='constant'),
            (n_epochs,self.hp['batch_sz'], -1, self.hp["backprop_len"])
        )
        y_batch=np.reshape(
            np.pad(y, (0, pad_len), mode='constant'),
            (n_epochs,self.hp['batch_sz'], -1, self.hp["backprop_len"])
        )
        n_batches=x_batch.shape[2]
        print(f"Started trainning: n_epochs={n_epochs} n_batches={n_batches}")
        self._train_graph()
        saver = tf.train.Saver()
        with tf.Session() as sess:
            
            train_writer = tf.summary.FileWriter( './mdl_tr', sess.graph)
#             sess.run(tf.initialize_all_variables())
            sess.run(tf.global_variables_initializer())
            losses=[]
            for epoch_num in range(n_epochs):
                curr_state = np.zeros([self.hp['batch_sz'], self.hp['state_sz']])
                for batch_idx in range(n_batches):
                    start = batch_idx*self.hp['batch_sz']
                    finish = start + self.hp['batch_sz']
                    summary, train_step, loss, curr_state, preds = sess.run(
#                     train_step, loss, curr_state, preds = sess.run(
                        [self.merged, self.train_step, self.total_loss, self.last_state, self.preds_seq],
#                         [self.train_step, self.total_loss, self.last_state, self.preds_seq],
                        feed_dict={
                            self.inputs_batch:x_batch[epoch_num,:,batch_idx,:],
                            self.labels_batch:y_batch[epoch_num,:,batch_idx,:],
                            self.init_state:curr_state
                        }
                    )
                    if batch_idx%100==0:
#                         train_writer.add_summary(summary, global_step=epoch_num)
                        saver.save(sess, self.hp['ckpt_path'] + "nn.mdl", global_step=epoch_num)
                        ypred = [1 if x[0]<0.5 else 0 for pred in preds for x in pred]
                        ytrue = [x for pred in y_batch[epoch_num,:,batch_idx,:] for x in pred]
                        print(f"epoch={epoch_num} batch_idx={batch_idx}")
                        print(f"ytrue={y_batch[epoch_num,0, batch_idx, :]}")
                        print(f"ypred={[x[1] for x in np.array(preds)[:,0,:]]}")
                        print(f"loss={loss}")

            
echo_step = 1
x = np.array(np.random.choice(2, 500000, p=[0.5, 0.5]))
y = np.roll(x, echo_step)
y[0:echo_step] = 0

rnn = RNN()
rnn.train(x, y, n_epochs=50)

Started trainning: n_epochs=50 n_batches=134
epoch=0 batch_idx=0
ytrue=[0 1 1 1 0 0 1 0 1 1 1 1 0 1 1]
ypred=[0.45999932, 0.35109955, 0.32599562, 0.32812956, 0.32860422, 0.3241758, 0.32795367, 0.32412425, 0.32368734, 0.32366654, 0.32366535, 0.32791322, 0.32411993, 0.32368705, 0.32366654]
loss=0.8442586064338684
epoch=0 batch_idx=100
ytrue=[1 0 0 1 1 0 0 1 0 0 1 0 1 0 0]
ypred=[0.5470528, 0.54718423, 0.54664987, 0.54648805, 0.54705292, 0.54718423, 0.54664981, 0.54705554, 0.54718512, 0.54664999, 0.54705566, 0.54663616, 0.54705518, 0.547185, 0.54719418]
loss=0.7088890671730042
epoch=1 batch_idx=0
ytrue=[0 0 1 0 0 0 1 0 1 1 1 1 1 1 1]
ypred=[0.51728433, 0.5503785, 0.51419729, 0.51408243, 0.51190412, 0.51120895, 0.51147914, 0.51114595, 0.51099622, 0.51099068, 0.51099038, 0.51099038, 0.51099038, 0.51099038, 0.51099032]
loss=0.695429801940918
epoch=1 batch_idx=100
ytrue=[1 1 1 1 0 1 1 1 1 1 0 0 1 0 0]
ypred=[0.50095475, 0.50095487, 0.50095493, 0.50102472, 0.50105929, 0.50095826, 0.5009551, 0.

epoch=15 batch_idx=100
ytrue=[1 1 0 1 1 1 1 0 1 1 1 1 1 1 1]
ypred=[0.99889249, 0.99930012, 0.00089196383, 0.99881941, 0.99890661, 0.99889344, 0.99929965, 0.00089133641, 0.99881881, 0.99890685, 0.99889332, 0.99890494, 0.99889874, 0.99890232, 0.99929488]
loss=0.0009645065874792635
epoch=16 batch_idx=0
ytrue=[0 0 0 0 0 0 0 1 0 1 1 1 0 0 1]
ypred=[0.26245639, 0.00043027746, 0.0047450964, 0.00062436261, 0.0016065127, 0.00079591875, 0.0011027645, 0.99941719, 0.0010954875, 0.99900597, 0.99882454, 0.99936408, 0.001034653, 0.00082859892, 0.99923325]
loss=0.03531138598918915
epoch=16 batch_idx=100
ytrue=[0 0 1 0 1 1 0 1 0 1 1 0 0 1 1]
ypred=[0.00091031846, 0.00079186197, 0.99931216, 0.00078527821, 0.99890816, 0.99938035, 0.00082942174, 0.99934226, 0.00082139287, 0.99894065, 0.99936205, 0.00091976259, 0.00080395793, 0.99892694, 0.9993698]
loss=0.0008508177706971765
epoch=17 batch_idx=0
ytrue=[0 1 1 1 1 1 0 1 1 0 1 1 1 0 0]
ypred=[0.330015, 0.99958855, 0.99386483, 0.99938059, 0.99839562, 0.999551

epoch=30 batch_idx=100
ytrue=[0 0 0 0 1 0 0 0 1 0 0 0 1 0 0]
ypred=[0.00045418297, 0.00043443911, 0.00043834274, 0.00032206104, 0.99971968, 0.0004491696, 0.00043779844, 0.00032327126, 0.99972063, 0.00045005445, 0.00043719602, 0.00032374499, 0.99972099, 0.00045042078, 0.00043694771]
loss=0.00037074272404424846
epoch=31 batch_idx=0
ytrue=[0 1 1 1 1 0 0 0 0 0 0 1 0 0 1]
ypred=[0.55703044, 0.99982494, 0.99731809, 0.99974018, 0.99937207, 0.00031095155, 0.00062245596, 0.00036343964, 0.00049376872, 0.00040033527, 0.00034745724, 0.99974269, 0.00046465354, 0.00030284142, 0.99956125]
loss=0.04934898018836975
epoch=31 batch_idx=100
ytrue=[0 1 1 0 0 0 0 0 0 1 1 0 0 0 1]
ypred=[0.00028592735, 0.99954969, 0.99975485, 0.00044259868, 0.00040916982, 0.00042227108, 0.00041329899, 0.00041891905, 0.00029457294, 0.99956316, 0.99974686, 0.00043491792, 0.00041399713, 0.00029908092, 0.99972147]
loss=0.00035299320006743073
epoch=32 batch_idx=0
ytrue=[0 0 1 1 1 0 0 0 0 1 0 1 0 1 0]
ypred=[0.36965698, 7.7893019e

epoch=44 batch_idx=100
ytrue=[1 1 1 1 0 0 0 1 1 0 1 0 0 0 0]
ypred=[0.99974912, 0.99974817, 0.999749, 0.99982303, 0.00030213894, 0.0002919824, 0.00019836778, 0.99974245, 0.9998228, 0.00020589038, 0.99981767, 0.00030033305, 0.00029315922, 0.00029204835, 0.00029230744]
loss=0.0002385669940849766
epoch=45 batch_idx=0
ytrue=[0 0 1 0 1 0 1 1 1 1 1 1 1 1 1]
ypred=[0.5081529, 4.8759943e-05, 0.99872476, 5.9808193e-05, 0.99907804, 6.6501387e-05, 0.99947518, 0.99980956, 0.99968708, 0.99977642, 0.99973005, 0.99976069, 0.99974304, 0.99975425, 0.99982053]
loss=0.06552381813526154
epoch=45 batch_idx=100
ytrue=[1 1 1 0 1 0 1 0 1 1 1 1 1 1 0]
ypred=[0.99971849, 0.99975151, 0.99982089, 0.00017467602, 0.99979931, 0.00015981452, 0.99977893, 0.00014592728, 0.99968696, 0.99976557, 0.99972516, 0.99975175, 0.99973613, 0.99983275, 0.00029339435]
loss=0.00022581909433938563
epoch=46 batch_idx=0
ytrue=[0 0 1 0 1 1 1 0 1 1 1 0 0 1 0]
ypred=[0.46304005, 4.6950503e-05, 0.99871206, 5.640529e-05, 0.99934822, 0.99981

In [12]:
from __future__ import print_function, division
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

num_epochs = 100
total_series_length = 50000
truncated_backprop_length = 15
state_size = 4
num_classes = 2
echo_step = 3
batch_size = 5
num_batches = total_series_length//batch_size//truncated_backprop_length

def plot(loss_list, predictions_series, batchX, batchY):
    plt.subplot(2, 3, 1)
    plt.cla()
    plt.plot(loss_list)

    for batch_series_idx in range(5):
        one_hot_output_series = np.array(predictions_series)[:, batch_series_idx, :]
        single_output_series = np.array([(1 if out[0] < 0.5 else 0) for out in one_hot_output_series])

        plt.subplot(2, 3, batch_series_idx + 2)
        plt.cla()
        plt.axis([0, truncated_backprop_length, 0, 2])
        left_offset = range(truncated_backprop_length)
        plt.bar(left_offset, batchX[batch_series_idx, :], width=1, color="blue")
        plt.bar(left_offset, batchY[batch_series_idx, :] * 0.5, width=1, color="red")
        plt.bar(left_offset, single_output_series * 0.3, width=1, color="green")

    plt.draw()
    plt.pause(0.0001)

def generateData():
    x = np.array(np.random.choice(2, total_series_length, p=[0.5, 0.5]))
    y = np.roll(x, echo_step)
    y[0:echo_step] = 0

    x = x.reshape((batch_size, -1))
    y = y.reshape((batch_size, -1))

    return (x, y)
    
class Test:
    def _init_graph(self):
        self.batchX_placeholder = tf.placeholder(tf.float32, [batch_size, truncated_backprop_length],name="xb")
        self.batchY_placeholder = tf.placeholder(tf.int32, [batch_size, truncated_backprop_length],name="yb")
        self.init_state = tf.placeholder(tf.float32, [batch_size, state_size],name="s0")
    
        self.W = tf.Variable(np.random.rand(state_size+1, state_size), dtype=tf.float32, name="W")
        self.b = tf.Variable(np.zeros((1,state_size)), dtype=tf.float32, name='b')
        self.W2 = tf.Variable(np.random.rand(state_size, num_classes),dtype=tf.float32, name="W2")
        self.b2 = tf.Variable(np.zeros((1,num_classes)), dtype=tf.float32, name="b2")
    
    def _forward(self):
        # Unpack columns
        self.inputs_series = tf.unstack(self.batchX_placeholder, axis=1)
        self.labels_series = tf.unstack(self.batchY_placeholder, axis=1)

        # Forward pass
        current_state = self.init_state
        states_series = []
        for current_input in self.inputs_series:
            current_input = tf.reshape(current_input, [batch_size, 1])
            input_and_state_concatenated = tf.concat([current_input, current_state], axis=1)

            next_state = tf.tanh(tf.matmul(input_and_state_concatenated, self.W) + self.b)  # Broadcasted addition
            states_series.append(next_state)
            current_state = next_state
        self.last_state = current_state
        self.logits_series = [tf.matmul(state, self.W2) + self.b2 for state in states_series]
        self.predictions_series = [tf.nn.softmax(logits) for logits in self.logits_series]
    
    def _train(self):
        losses = [tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=labels) for logits, labels in zip(self.logits_series, self.labels_series)]
        self.total_loss = tf.reduce_mean(losses)
        self.train_step = tf.train.AdagradOptimizer(0.3).minimize(self.total_loss)
    
    def train(self, x, y, n_epochs=100):
        self._init_graph()
        self._forward()
        self._train()
        
        nobs = len(x)
        divider = batch_size*truncated_backprop_length*n_epochs
        pad_len = divider - (nobs%divider)
        if nobs<pad_len:
            raise Exception("Wrong n_epochs({n_epochs}): choose smaller value.")
        
        x_batch=np.reshape(
            np.pad(x, (0, pad_len), mode='constant'),
            (n_epochs,batch_size, -1, truncated_backprop_length)
        )
        y_batch=np.reshape(
            np.pad(y, (0, pad_len), mode='constant'),
            (n_epochs,batch_size, -1, truncated_backprop_length)
        )
        n_batches=x_batch.shape[1]
        
        with tf.Session() as sess:
            sess.run(tf.initialize_all_variables())
            plt.ion()
            plt.figure()
            plt.show()
            loss_list = []

            for epoch_idx in range(num_epochs):
#                 x,y = generateData()
                _current_state = np.zeros((batch_size, state_size))

                print("New data, epoch", epoch_idx)

                for batch_idx in range(num_batches):
                    start_idx = batch_idx * truncated_backprop_length
                    end_idx = start_idx + truncated_backprop_length

#                     batchX = x[:,start_idx:end_idx]
#                     batchY = y[:,start_idx:end_idx]
                    
                    
                    _total_loss, _train_step, _current_state, _predictions_series = sess.run(
                        [self.total_loss, self.train_step, self.last_state, self.predictions_series],
                        feed_dict={
#                             self.batchX_placeholder:batchX,
#                             self.batchY_placeholder:batchY,
                            self.batchX_placeholder:x_batch[epoch_idx, :,batch_idx,:],
                            self.batchY_placeholder:y_batch[epoch_idx, :,batch_idx,:],
                            self.init_state:_current_state
                        }
                    )

                    loss_list.append(_total_loss)

                    if batch_idx%100 == 0:
                        print("Step",batch_idx, "Loss", _total_loss)
#                         plot(loss_list, _predictions_series, batchX, batchY)
#                         plot(loss_list, _predictions_series, x_batch[epoch_idx,:,batch_idx,:], y_batch[epoch_idx,:,batch_idx,:])
                        print(y_batch[epoch_idx,0, batch_idx, :])
                        print(np.array(_predictions_series)[:,0,:])

        plt.ioff()
        plt.show()

echo_step = 1
x = np.array(np.random.choice(2, 5000000, p=[0.5, 0.5]))
y = np.roll(x, echo_step)
y[0:echo_step] = 0
        
tst = Test()
tst.train(x,y)

<Figure size 432x288 with 0 Axes>

New data, epoch 0
Step 0 Loss 0.69896
[0 0 1 1 1 0 0 1 0 1 1 1 1 1 0]
[[ 0.5         0.5       ]
 [ 0.4686639   0.53133613]
 [ 0.44860706  0.55139297]
 [ 0.45085731  0.54914278]
 [ 0.45120201  0.54879802]
 [ 0.45117897  0.54882097]
 [ 0.45141613  0.54858381]
 [ 0.45128796  0.54871207]
 [ 0.45142812  0.54857188]
 [ 0.45149663  0.54850334]
 [ 0.45150131  0.54849869]
 [ 0.45150176  0.54849833]
 [ 0.45150176  0.54849821]
 [ 0.45129752  0.54870242]
 [ 0.45119309  0.54880685]]
Step 100 Loss 0.692492
[0 1 0 0 1 1 1 0 1 1 0 0 1 0 1]
[[ 0.47305369  0.52694631]
 [ 0.47323301  0.52676702]
 [ 0.47321156  0.52678841]
 [ 0.47305346  0.52694649]
 [ 0.47307798  0.52692211]
 [ 0.47307888  0.52692115]
 [ 0.4732348   0.52676523]
 [ 0.47305617  0.5269438 ]
 [ 0.4730781   0.52692193]
 [ 0.47323462  0.52676541]
 [ 0.47321197  0.52678806]
 [ 0.47305346  0.52694649]
 [ 0.47323301  0.52676702]
 [ 0.47305599  0.52694404]
 [ 0.47323331  0.52676666]]
Step 200 Loss 0.711866
[0 0 1 0 1 0 0 0 0 1 1 1 0 0 1]
[[ 0.432

Step 400 Loss 0.000916789
[1 1 1 1 0 0 1 1 1 0 1 1 1 1 0]
[[  8.56864732e-04   9.99143124e-01]
 [  8.44333379e-04   9.99155641e-01]
 [  8.47365474e-04   9.99152660e-01]
 [  9.88011714e-04   9.99011993e-01]
 [  9.99222398e-01   7.77583453e-04]
 [  9.99004304e-01   9.95665323e-04]
 [  8.55496561e-04   9.99144435e-01]
 [  8.44405033e-04   9.99155641e-01]
 [  9.88287386e-04   9.99011636e-01]
 [  9.98936236e-01   1.06380216e-03]
 [  8.30814592e-04   9.99169230e-01]
 [  8.46880372e-04   9.99153137e-01]
 [  8.47424380e-04   9.99152541e-01]
 [  9.88011714e-04   9.99011993e-01]
 [  9.98936236e-01   1.06379250e-03]]
Step 500 Loss 0.000840607
[1 1 0 0 0 1 1 0 1 1 0 0 0 0 1]
[[  7.99539499e-04   9.99200523e-01]
 [  9.13489785e-04   9.99086499e-01]
 [  9.99276102e-01   7.23884499e-04]
 [  9.99319673e-01   6.80313387e-04]
 [  9.99065220e-01   9.34743497e-04]
 [  8.01217044e-04   9.99198854e-01]
 [  9.13330470e-04   9.99086618e-01]
 [  9.99014020e-01   9.85963154e-04]
 [  7.75860390e-04   9.99224186e

Step 400 Loss 0.000443173
[1 0 1 0 1 0 0 0 0 1 0 0 0 1 0]
[[  4.74924222e-04   9.99525070e-01]
 [  9.99472082e-01   5.27936616e-04]
 [  4.60550596e-04   9.99539495e-01]
 [  9.99459088e-01   5.40882931e-04]
 [  4.55463713e-04   9.99544561e-01]
 [  9.99594629e-01   4.05355415e-04]
 [  9.99626637e-01   3.73319286e-04]
 [  9.99620914e-01   3.79114674e-04]
 [  9.99493361e-01   5.06665150e-04]
 [  4.82901261e-04   9.99517083e-01]
 [  9.99606550e-01   3.93431168e-04]
 [  9.99625444e-01   3.74535215e-04]
 [  9.99492884e-01   5.07145654e-04]
 [  4.82788746e-04   9.99517202e-01]
 [  9.99474466e-01   5.25578333e-04]]
Step 500 Loss 0.000422257
[1 1 0 0 0 1 1 0 0 1 1 1 1 0 1]
[[  4.16731404e-04   9.99583304e-01]
 [  4.57534392e-04   9.99542475e-01]
 [  9.99619961e-01   3.80037411e-04]
 [  9.99639392e-01   3.60562844e-04]
 [  9.99512553e-01   4.87427606e-04]
 [  4.16748488e-04   9.99583304e-01]
 [  4.57530667e-04   9.99542475e-01]
 [  9.99619961e-01   3.80037760e-04]
 [  9.99520898e-01   4.79073409e

Step 400 Loss 0.000298244
[0 1 0 1 0 1 0 0 0 1 1 1 1 1 0]
[[  9.99658704e-01   3.41251434e-04]
 [  3.03062407e-04   9.99696970e-01]
 [  9.99655247e-01   3.44723347e-04]
 [  2.94423022e-04   9.99705493e-01]
 [  9.99647856e-01   3.52136674e-04]
 [  2.91583448e-04   9.99708354e-01]
 [  9.99711335e-01   2.88658164e-04]
 [  9.99727190e-01   2.72792357e-04]
 [  9.99658585e-01   3.41454521e-04]
 [  2.87032744e-04   9.99713004e-01]
 [  2.81709421e-04   9.99718249e-01]
 [  2.82891764e-04   9.99717057e-01]
 [  2.82755034e-04   9.99717176e-01]
 [  2.98204861e-04   9.99701798e-01]
 [  9.99651551e-01   3.48426664e-04]]
Step 500 Loss 0.00029656
[0 1 0 0 1 1 1 0 0 0 0 0 1 0 0]
[[  9.99662519e-01   3.37457517e-04]
 [  2.87295814e-04   9.99712646e-01]
 [  9.99721229e-01   2.78808468e-04]
 [  9.99675274e-01   3.24783701e-04]
 [  2.81207089e-04   9.99718726e-01]
 [  2.74990569e-04   9.99725044e-01]
 [  2.91900855e-04   9.99708116e-01]
 [  9.99724090e-01   2.75881059e-04]
 [  9.99733508e-01   2.66430114e-

Step 400 Loss 0.000223694
[0 1 0 1 0 0 1 0 1 1 0 0 0 0 1]
[[  9.99760687e-01   2.39300964e-04]
 [  2.37921849e-04   9.99762118e-01]
 [  9.99766886e-01   2.33077386e-04]
 [  2.36525855e-04   9.99763429e-01]
 [  9.99799073e-01   2.00895331e-04]
 [  9.99761760e-01   2.38299632e-04]
 [  2.38142675e-04   9.99761879e-01]
 [  9.99767005e-01   2.32945196e-04]
 [  2.21980968e-04   9.99777973e-01]
 [  2.27913100e-04   9.99772131e-01]
 [  9.99795854e-01   2.04175900e-04]
 [  9.99797642e-01   2.02339812e-04]
 [  9.99795854e-01   2.04152137e-04]
 [  9.99760687e-01   2.39301415e-04]
 [  2.37922082e-04   9.99762118e-01]]
Step 500 Loss 0.000219675
[0 1 1 1 1 0 0 0 1 0 1 0 1 1 0]
[[  9.99766648e-01   2.33385188e-04]
 [  2.18697620e-04   9.99781311e-01]
 [  2.10318787e-04   9.99789655e-01]
 [  2.12250525e-04   9.99787748e-01]
 [  2.25526863e-04   9.99774516e-01]
 [  9.99800026e-01   1.99962757e-04]
 [  9.99801457e-01   1.98611364e-04]
 [  9.99764740e-01   2.35255357e-04]
 [  2.33017403e-04   9.99767005e

Step 400 Loss 0.000177838
[0 1 1 1 0 0 0 1 1 1 1 1 0 0 1]
[[  9.99814689e-01   1.85386365e-04]
 [  1.76340283e-04   9.99823630e-01]
 [  1.72288928e-04   9.99827623e-01]
 [  1.81871190e-04   9.99818146e-01]
 [  9.99836564e-01   1.63447083e-04]
 [  9.99837995e-01   1.62007491e-04]
 [  9.99810994e-01   1.89068596e-04]
 [  1.77606213e-04   9.99822438e-01]
 [  1.72077780e-04   9.99827862e-01]
 [  1.73731052e-04   9.99826252e-01]
 [  1.73446882e-04   9.99826610e-01]
 [  1.81612282e-04   9.99818385e-01]
 [  9.99836445e-01   1.63502889e-04]
 [  9.99812901e-01   1.87078593e-04]
 [  1.86247082e-04   9.99813735e-01]]
Step 500 Loss 0.000174258
[0 0 1 0 0 1 1 0 1 0 0 1 1 0 1]
[[  9.99838471e-01   1.61498363e-04]
 [  9.99815881e-01   1.84147328e-04]
 [  1.83271128e-04   9.99816716e-01]
 [  9.99841094e-01   1.58891446e-04]
 [  9.99815047e-01   1.84980585e-04]
 [  1.75039168e-04   9.99824941e-01]
 [  1.77076436e-04   9.99822915e-01]
 [  9.99814212e-01   1.85845114e-04]
 [  1.79020120e-04   9.99821007e

Step 400 Loss 0.000147926
[1 0 1 1 1 1 1 0 1 0 1 1 0 1 0]
[[  1.50868917e-04   9.99849081e-01]
 [  9.99849200e-01   1.50812397e-04]
 [  1.49613261e-04   9.99850392e-01]
 [  1.47445404e-04   9.99852538e-01]
 [  1.48510429e-04   9.99851465e-01]
 [  1.48286446e-04   9.99851704e-01]
 [  1.50569133e-04   9.99849439e-01]
 [  9.99849081e-01   1.50896114e-04]
 [  1.51112807e-04   9.99848843e-01]
 [  9.99849558e-01   1.50459193e-04]
 [  1.49845408e-04   9.99850154e-01]
 [  1.49547923e-04   9.99850392e-01]
 [  9.99848723e-01   1.51264612e-04]
 [  1.50843873e-04   9.99849081e-01]
 [  9.99864578e-01   1.35387614e-04]]
Step 500 Loss 0.000145323
[1 1 1 1 1 1 1 0 1 0 0 0 1 0 0]
[[  1.47143423e-04   9.99852777e-01]
 [  1.45662852e-04   9.99854326e-01]
 [  1.46572929e-04   9.99853373e-01]
 [  1.46374601e-04   9.99853611e-01]
 [  1.46408958e-04   9.99853611e-01]
 [  1.46403079e-04   9.99853611e-01]
 [  1.48602936e-04   9.99851346e-01]
 [  9.99850869e-01   1.49151034e-04]
 [  1.48894687e-04   9.99851108e

Step 400 Loss 0.000125311
[1 1 0 0 0 0 0 1 0 0 0 0 0 0 0]
[[  1.24577782e-04   9.99875426e-01]
 [  1.25371458e-04   9.99874592e-01]
 [  9.99881148e-01   1.18823315e-04]
 [  9.99882579e-01   1.17443960e-04]
 [  9.99881268e-01   1.18709162e-04]
 [  9.99881625e-01   1.18414544e-04]
 [  9.99866247e-01   1.33776586e-04]
 [  1.26763975e-04   9.99873161e-01]
 [  9.99882102e-01   1.17866584e-04]
 [  9.99882340e-01   1.17703399e-04]
 [  9.99881387e-01   1.18652577e-04]
 [  9.99881506e-01   1.18426498e-04]
 [  9.99881506e-01   1.18474956e-04]
 [  9.99881506e-01   1.18464675e-04]
 [  9.99866247e-01   1.33763955e-04]]
Step 500 Loss 0.000124246
[1 1 1 0 0 0 0 1 1 0 1 0 1 0 1]
[[  1.22234022e-04   9.99877810e-01]
 [  1.22235404e-04   9.99877691e-01]
 [  1.24828686e-04   9.99875188e-01]
 [  9.99882817e-01   1.17200303e-04]
 [  9.99883771e-01   1.16217067e-04]
 [  9.99882579e-01   1.17367155e-04]
 [  9.99867797e-01   1.32225192e-04]
 [  1.23294260e-04   9.99876738e-01]
 [  1.24028506e-04   9.99875903e

Step 400 Loss 0.000110239
[0 1 0 1 1 1 0 1 0 1 0 0 0 1 1]
[[  9.99877810e-01   1.22158046e-04]
 [  1.11093606e-04   9.99888897e-01]
 [  9.99879956e-01   1.20064105e-04]
 [  1.02744183e-04   9.99897242e-01]
 [  1.03036466e-04   9.99897003e-01]
 [  1.10753659e-04   9.99889255e-01]
 [  9.99878764e-01   1.21221157e-04]
 [  1.08927234e-04   9.99891043e-01]
 [  9.99878049e-01   1.21899022e-04]
 [  1.08563465e-04   9.99891400e-01]
 [  9.99896169e-01   1.03812228e-04]
 [  9.99897718e-01   1.02324244e-04]
 [  9.99877691e-01   1.22330341e-04]
 [  1.03839753e-04   9.99896169e-01]
 [  1.02767212e-04   9.99897242e-01]]
Step 500 Loss 0.000108149
[0 0 1 1 1 1 1 0 1 1 0 1 1 1 1]
[[  9.99897957e-01   1.01995553e-04]
 [  9.99880314e-01   1.19709490e-04]
 [  1.03174105e-04   9.99896765e-01]
 [  1.01734266e-04   9.99898314e-01]
 [  1.02422942e-04   9.99897599e-01]
 [  1.02261423e-04   9.99897718e-01]
 [  1.09748602e-04   9.99890208e-01]
 [  9.99880195e-01   1.19814547e-04]
 [  1.01438134e-04   9.99898553e

Step 400 Loss 9.6868e-05
[0 1 0 0 1 0 1 0 0 1 1 0 1 0 1]
[[  9.99898911e-01   1.01134669e-04]
 [  1.00753961e-04   9.99899268e-01]
 [  9.99911070e-01   8.89244184e-05]
 [  9.99898672e-01   1.01354977e-04]
 [  1.00687685e-04   9.99899268e-01]
 [  9.99901533e-01   9.84841608e-05]
 [  1.00455887e-04   9.99899507e-01]
 [  9.99910951e-01   8.90716692e-05]
 [  9.99898672e-01   1.01297388e-04]
 [  9.78085300e-05   9.99902129e-01]
 [  9.78563912e-05   9.99902129e-01]
 [  9.99899387e-01   1.00640849e-04]
 [  9.88623215e-05   9.99901175e-01]
 [  9.99900341e-01   9.96796371e-05]
 [  9.95584269e-05   9.99900460e-01]]
Step 500 Loss 9.61528e-05
[1 0 1 1 0 0 1 0 0 0 1 0 0 1 0]
[[  9.70670808e-05   9.99902964e-01]
 [  9.99900103e-01   9.98496325e-05]
 [  9.53386916e-05   9.99904633e-01]
 [  9.74567956e-05   9.99902487e-01]
 [  9.99910116e-01   8.98675862e-05]
 [  9.99900103e-01   9.99338517e-05]
 [  9.98939213e-05   9.99900103e-01]
 [  9.99911785e-01   8.81687956e-05]
 [  9.99909520e-01   9.04463450e-

Step 400 Loss 8.7054e-05
[1 1 1 0 0 0 0 0 0 0 0 0 0 0 1]
[[  8.31270227e-05   9.99916911e-01]
 [  8.30205463e-05   9.99917030e-01]
 [  8.60777800e-05   9.99913931e-01]
 [  9.99915123e-01   8.49275821e-05]
 [  9.99915600e-01   8.43937814e-05]
 [  9.99914765e-01   8.52454759e-05]
 [  9.99915004e-01   8.50064171e-05]
 [  9.99914885e-01   8.50682918e-05]
 [  9.99914885e-01   8.50522265e-05]
 [  9.99914885e-01   8.50564466e-05]
 [  9.99914885e-01   8.50552242e-05]
 [  9.99914885e-01   8.50555516e-05]
 [  9.99914885e-01   8.50555516e-05]
 [  9.99904156e-01   9.58358287e-05]
 [  8.29759083e-05   9.99917030e-01]]
Step 500 Loss 8.68378e-05
[1 0 0 0 0 1 0 1 1 1 0 1 0 1 0]
[[  8.54970422e-05   9.99914527e-01]
 [  9.99915838e-01   8.41758883e-05]
 [  9.99916315e-01   8.37299012e-05]
 [  9.99915481e-01   8.45461909e-05]
 [  9.99905109e-01   9.49256719e-05]
 [  8.52294615e-05   9.99914765e-01]
 [  9.99906063e-01   9.39290621e-05]
 [  8.13726874e-05   9.99918580e-01]
 [  8.23973169e-05   9.99917626e-

Step 400 Loss 7.95364e-05
[0 1 1 1 0 1 0 0 0 0 0 0 1 0 0]
[[  9.99915481e-01   8.45671602e-05]
 [  7.45325597e-05   9.99925494e-01]
 [  7.38713861e-05   9.99926090e-01]
 [  8.01396527e-05   9.99919891e-01]
 [  9.99914289e-01   8.57387058e-05]
 [  7.93165746e-05   9.99920726e-01]
 [  9.99925375e-01   7.46658043e-05]
 [  9.99924541e-01   7.54796929e-05]
 [  9.99924183e-01   7.58263413e-05]
 [  9.99924302e-01   7.57188900e-05]
 [  9.99924302e-01   7.57480739e-05]
 [  9.99912858e-01   8.71898228e-05]
 [  8.03293951e-05   9.99919653e-01]
 [  9.99925971e-01   7.40253236e-05]
 [  9.99912858e-01   8.71731900e-05]]
Step 500 Loss 7.89834e-05
[0 0 1 0 1 0 1 0 1 1 1 0 1 1 0]
[[  9.99924779e-01   7.52116903e-05]
 [  9.99913454e-01   8.65055845e-05]
 [  7.98607362e-05   9.99920130e-01]
 [  9.99916077e-01   8.39059794e-05]
 [  7.95497981e-05   9.99920487e-01]
 [  9.99915838e-01   8.41483634e-05]
 [  7.93989821e-05   9.99920607e-01]
 [  9.99915719e-01   8.42746012e-05]
 [  7.38673698e-05   9.99926090e

Step 400 Loss 7.2235e-05
[1 0 1 0 1 0 1 1 1 0 1 1 0 0 0]
[[  7.29726744e-05   9.99927044e-01]
 [  9.99926209e-01   7.38113886e-05]
 [  7.39219831e-05   9.99926090e-01]
 [  9.99926925e-01   7.31027831e-05]
 [  7.44436256e-05   9.99925494e-01]
 [  9.99927282e-01   7.27291117e-05]
 [  7.19380114e-05   9.99927998e-01]
 [  6.85224368e-05   9.99931455e-01]
 [  7.25822974e-05   9.99927402e-01]
 [  9.99925017e-01   7.50004110e-05]
 [  7.05327839e-05   9.99929428e-01]
 [  7.15632705e-05   9.99928474e-01]
 [  9.99929786e-01   7.02436882e-05]
 [  9.99929190e-01   7.08284133e-05]
 [  9.99928713e-01   7.12393012e-05]]
Step 500 Loss 7.13545e-05
[1 1 1 1 0 0 1 1 1 0 1 0 1 1 0]
[[  6.97738942e-05   9.99930263e-01]
 [  6.85597042e-05   9.99931455e-01]
 [  6.92879403e-05   9.99930739e-01]
 [  7.17703442e-05   9.99928236e-01]
 [  9.99930501e-01   6.95308627e-05]
 [  9.99924064e-01   7.59438553e-05]
 [  7.05144848e-05   9.99929428e-01]
 [  6.83534818e-05   9.99931693e-01]
 [  7.20564567e-05   9.99927998e-

Step 400 Loss 6.59667e-05
[1 1 1 1 0 1 0 1 0 1 1 1 1 1 1]
[[  6.61334489e-05   9.99933839e-01]
 [  6.35681281e-05   9.99936461e-01]
 [  6.47390334e-05   9.99935269e-01]
 [  6.65777770e-05   9.99933362e-01]
 [  9.99931097e-01   6.88477085e-05]
 [  6.69107249e-05   9.99933124e-01]
 [  9.99932051e-01   6.78898505e-05]
 [  6.75892807e-05   9.99932408e-01]
 [  9.99932647e-01   6.73778850e-05]
 [  6.58583667e-05   9.99934196e-01]
 [  6.36506811e-05   9.99936342e-01]
 [  6.47147681e-05   9.99935269e-01]
 [  6.44038737e-05   9.99935627e-01]
 [  6.44891697e-05   9.99935508e-01]
 [  6.44656320e-05   9.99935508e-01]]
Step 500 Loss 6.60859e-05
[1 0 1 1 0 1 0 1 0 1 1 1 1 0 0]
[[  6.71663147e-05   9.99932885e-01]
 [  9.99933004e-01   6.69990914e-05]
 [  6.54250034e-05   9.99934554e-01]
 [  6.54348623e-05   9.99934554e-01]
 [  9.99931216e-01   6.87769716e-05]
 [  6.62672828e-05   9.99933720e-01]
 [  9.99932289e-01   6.76838972e-05]
 [  6.70337322e-05   9.99933004e-01]
 [  9.99932885e-01   6.70977461e

Step 400 Loss 6.15419e-05
[1 0 1 0 0 0 1 1 0 1 0 0 1 1 0]
[[  6.02665023e-05   9.99939680e-01]
 [  9.99936223e-01   6.37833873e-05]
 [  6.07863731e-05   9.99939203e-01]
 [  9.99939919e-01   6.00868298e-05]
 [  9.99938607e-01   6.14262608e-05]
 [  9.99935389e-01   6.45583350e-05]
 [  6.06365975e-05   9.99939322e-01]
 [  6.04107518e-05   9.99939561e-01]
 [  9.99936223e-01   6.37198464e-05]
 [  6.08295195e-05   9.99939203e-01]
 [  9.99939919e-01   6.00548046e-05]
 [  9.99935508e-01   6.44926185e-05]
 [  6.06573594e-05   9.99939322e-01]
 [  6.04037232e-05   9.99939561e-01]
 [  9.99939203e-01   6.08401933e-05]]
Step 500 Loss 6.11159e-05
[0 0 0 1 1 0 0 0 1 0 1 1 1 0 0]
[[  9.99938846e-01   6.11113865e-05]
 [  9.99938846e-01   6.11402429e-05]
 [  9.99935865e-01   6.41699371e-05]
 [  6.02928849e-05   9.99939680e-01]
 [  6.00977146e-05   9.99939919e-01]
 [  9.99939561e-01   6.04828674e-05]
 [  9.99939203e-01   6.07972142e-05]
 [  9.99935746e-01   6.42902960e-05]
 [  6.11795549e-05   9.99938846e

Step 400 Loss 5.73126e-05
[1 0 0 0 1 1 0 0 1 0 0 0 0 0 1]
[[  5.76500570e-05   9.99942303e-01]
 [  9.99945164e-01   5.48178177e-05]
 [  9.99943733e-01   5.62334208e-05]
 [  9.99939203e-01   6.07357288e-05]
 [  5.58050961e-05   9.99944210e-01]
 [  5.73815814e-05   9.99942660e-01]
 [  9.99944448e-01   5.55193074e-05]
 [  9.99939561e-01   6.04648740e-05]
 [  5.78731378e-05   9.99942064e-01]
 [  9.99945283e-01   5.46680931e-05]
 [  9.99943733e-01   5.62953937e-05]
 [  9.99943733e-01   5.62067762e-05]
 [  9.99943733e-01   5.62239293e-05]
 [  9.99939322e-01   6.07278016e-05]
 [  5.77886531e-05   9.99942183e-01]]
Step 500 Loss 5.68533e-05
[0 0 0 0 1 1 0 0 1 0 0 0 1 0 1]
[[  9.99944091e-01   5.59270920e-05]
 [  9.99944091e-01   5.59263462e-05]
 [  9.99944091e-01   5.59266118e-05]
 [  9.99939561e-01   6.04199122e-05]
 [  5.55031584e-05   9.99944448e-01]
 [  5.70977354e-05   9.99942899e-01]
 [  9.99944806e-01   5.52281417e-05]
 [  9.99939799e-01   6.01558531e-05]
 [  5.75739650e-05   9.99942422e

Step 400 Loss 5.35728e-05
[0 0 0 0 0 0 1 0 1 1 0 1 0 0 1]
[[  9.99947906e-01   5.20855065e-05]
 [  9.99947667e-01   5.22836199e-05]
 [  9.99947786e-01   5.22114242e-05]
 [  9.99947786e-01   5.22345326e-05]
 [  9.99947786e-01   5.22271584e-05]
 [  9.99944091e-01   5.58832144e-05]
 [  5.45755320e-05   9.99945402e-01]
 [  9.99945998e-01   5.40472065e-05]
 [  5.32465274e-05   9.99946713e-01]
 [  5.38754321e-05   9.99946117e-01]
 [  9.99944925e-01   5.50773475e-05]
 [  5.39642315e-05   9.99945998e-01]
 [  9.99948978e-01   5.10371392e-05]
 [  9.99944091e-01   5.58639804e-05]
 [  5.30739635e-05   9.99946952e-01]]
Step 500 Loss 5.32216e-05
[0 0 0 0 0 1 0 1 0 0 0 0 1 1 0]
[[  9.99949574e-01   5.03960691e-05]
 [  9.99947906e-01   5.21089096e-05]
 [  9.99948025e-01   5.19370078e-05]
 [  9.99948025e-01   5.19829882e-05]
 [  9.99944329e-01   5.56209998e-05]
 [  5.42974412e-05   9.99945641e-01]
 [  9.99946237e-01   5.38134627e-05]
 [  5.44613104e-05   9.99945521e-01]
 [  9.99949694e-01   5.02845542e

Step 400 Loss 5.08518e-05
[0 0 0 0 0 1 0 1 0 1 1 0 1 1 1]
[[  9.99949217e-01   5.08040066e-05]
 [  9.99948502e-01   5.15013126e-05]
 [  9.99948263e-01   5.17713052e-05]
 [  9.99948382e-01   5.16719192e-05]
 [  9.99944329e-01   5.56931336e-05]
 [  4.87349789e-05   9.99951243e-01]
 [  9.99945521e-01   5.44974719e-05]
 [  4.83560616e-05   9.99951601e-01]
 [  9.99945164e-01   5.48864482e-05]
 [  4.60432348e-05   9.99953985e-01]
 [  4.92902946e-05   9.99950767e-01]
 [  9.99945045e-01   5.49409597e-05]
 [  4.60206720e-05   9.99953985e-01]
 [  4.69525658e-05   9.99953032e-01]
 [  4.92394611e-05   9.99950767e-01]]
Step 500 Loss 5.0224e-05
[0 0 0 1 0 1 1 1 1 0 1 1 0 1 1]
[[  9.99949098e-01   5.08702760e-05]
 [  9.99948859e-01   5.11296457e-05]
 [  9.99944448e-01   5.54897197e-05]
 [  4.85691635e-05   9.99951482e-01]
 [  9.99945879e-01   5.41274094e-05]
 [  4.60942792e-05   9.99953866e-01]
 [  4.66448982e-05   9.99953389e-01]
 [  4.67319842e-05   9.99953270e-01]
 [  4.90653256e-05   9.99950886e-

Step 400 Loss 4.74919e-05
[0 1 0 1 0 0 1 0 1 0 0 1 0 0 0]
[[  9.99952912e-01   4.71333587e-05]
 [  4.92062682e-05   9.99950767e-01]
 [  9.99953389e-01   4.65966114e-05]
 [  4.96713146e-05   9.99950290e-01]
 [  9.99955773e-01   4.41760021e-05]
 [  9.99950171e-01   4.98753725e-05]
 [  4.84335978e-05   9.99951601e-01]
 [  9.99952793e-01   4.71512467e-05]
 [  4.91903629e-05   9.99950767e-01]
 [  9.99955535e-01   4.44733669e-05]
 [  9.99950290e-01   4.97296605e-05]
 [  4.84873417e-05   9.99951482e-01]
 [  9.99955058e-01   4.49344625e-05]
 [  9.99952912e-01   4.71301682e-05]
 [  9.99950886e-01   4.90809070e-05]]
Step 500 Loss 4.71787e-05
[0 0 1 1 1 1 0 1 0 0 0 0 0 1 0]
[[  9.99955297e-01   4.47174316e-05]
 [  9.99950647e-01   4.93356238e-05]
 [  4.67654208e-05   9.99953270e-01]
 [  4.58592731e-05   9.99954104e-01]
 [  4.65403937e-05   9.99953508e-01]
 [  4.79311166e-05   9.99952078e-01]
 [  9.99952078e-01   4.78860165e-05]
 [  4.81964089e-05   9.99951839e-01]
 [  9.99955177e-01   4.47941711e

Step 400 Loss 4.4596e-05
[1 1 0 1 0 0 1 1 0 1 1 0 0 1 0]
[[  4.33220594e-05   9.99956727e-01]
 [  4.44404250e-05   9.99955535e-01]
 [  9.99953151e-01   4.68830804e-05]
 [  4.38052484e-05   9.99956250e-01]
 [  9.99955297e-01   4.46993981e-05]
 [  9.99952435e-01   4.75048219e-05]
 [  4.31237895e-05   9.99956846e-01]
 [  4.41919292e-05   9.99955773e-01]
 [  9.99953032e-01   4.70065534e-05]
 [  4.26065380e-05   9.99957442e-01]
 [  4.43822391e-05   9.99955654e-01]
 [  9.99955058e-01   4.49222098e-05]
 [  9.99952555e-01   4.74207263e-05]
 [  4.43206518e-05   9.99955654e-01]
 [  9.99955773e-01   4.42779892e-05]]
Step 500 Loss 4.49314e-05
[0 0 0 0 0 0 1 1 1 0 0 1 1 0 1]
[[  9.99955297e-01   4.46705926e-05]
 [  9.99954820e-01   4.51407432e-05]
 [  9.99954581e-01   4.54253677e-05]
 [  9.99954700e-01   4.53189714e-05]
 [  9.99954700e-01   4.53553766e-05]
 [  9.99952555e-01   4.74295412e-05]
 [  4.29183347e-05   9.99957085e-01]
 [  4.27591694e-05   9.99957204e-01]
 [  4.44158941e-05   9.99955535e-

Step 400 Loss 4.25695e-05
[0 0 1 1 1 1 1 1 1 0 0 1 0 0 0]
[[  9.99958992e-01   4.10029425e-05]
 [  9.99956965e-01   4.29844004e-05]
 [  4.38469542e-05   9.99956131e-01]
 [  4.31096487e-05   9.99956846e-01]
 [  4.37898307e-05   9.99956250e-01]
 [  4.35458460e-05   9.99956489e-01]
 [  4.36279406e-05   9.99956369e-01]
 [  4.36001537e-05   9.99956369e-01]
 [  4.39788237e-05   9.99956012e-01]
 [  9.99959946e-01   4.00715653e-05]
 [  9.99956965e-01   4.29907523e-05]
 [  4.41094089e-05   9.99955893e-01]
 [  9.99960542e-01   3.94651615e-05]
 [  9.99958754e-01   4.12679692e-05]
 [  9.99957085e-01   4.29040520e-05]]
Step 500 Loss 4.24011e-05
[0 1 0 1 0 0 1 0 0 1 0 1 1 0 0]
[[  9.99958038e-01   4.19084208e-05]
 [  4.37047638e-05   9.99956250e-01]
 [  9.99958515e-01   4.14541755e-05]
 [  4.41218617e-05   9.99955893e-01]
 [  9.99960780e-01   3.91995600e-05]
 [  9.99956846e-01   4.31558401e-05]
 [  4.37439630e-05   9.99956250e-01]
 [  9.99960542e-01   3.94395029e-05]
 [  9.99956965e-01   4.30512300e

Step 400 Loss 4.05144e-05
[0 0 1 1 1 1 0 0 1 1 1 1 0 0 0]
[[  9.99959350e-01   4.06706422e-05]
 [  9.99956131e-01   4.38126372e-05]
 [  3.80990714e-05   9.99961853e-01]
 [  3.88754634e-05   9.99961138e-01]
 [  3.88757944e-05   9.99961138e-01]
 [  4.05937608e-05   9.99959350e-01]
 [  9.99959946e-01   4.01017642e-05]
 [  9.99956369e-01   4.36036898e-05]
 [  3.81568898e-05   9.99961853e-01]
 [  3.88498520e-05   9.99961138e-01]
 [  3.88847693e-05   9.99961138e-01]
 [  4.05906248e-05   9.99959350e-01]
 [  9.99959946e-01   4.01031793e-05]
 [  9.99959588e-01   4.03527265e-05]
 [  9.99959350e-01   4.06847212e-05]]
Step 500 Loss 4.04143e-05
[1 1 0 0 1 1 1 1 0 1 0 0 1 0 1]
[[  3.75292839e-05   9.99962449e-01]
 [  4.06534637e-05   9.99959350e-01]
 [  9.99960184e-01   3.98527809e-05]
 [  9.99956489e-01   4.34618742e-05]
 [  3.80235433e-05   9.99961972e-01]
 [  3.87058535e-05   9.99961257e-01]
 [  3.87444052e-05   9.99961257e-01]
 [  4.04579223e-05   9.99959588e-01]
 [  9.99956965e-01   4.30439650e

Step 400 Loss 3.95099e-05
[0 0 1 1 0 1 0 1 0 0 1 0 0 1 1]
[[  9.99960542e-01   3.94668568e-05]
 [  9.99955177e-01   4.48358878e-05]
 [  3.38514074e-05   9.99966145e-01]
 [  3.87744585e-05   9.99961257e-01]
 [  9.99955893e-01   4.41111733e-05]
 [  3.66591084e-05   9.99963284e-01]
 [  9.99954581e-01   4.53607354e-05]
 [  3.60484082e-05   9.99963999e-01]
 [  9.99959469e-01   4.05547980e-05]
 [  9.99956250e-01   4.37544368e-05]
 [  3.74473457e-05   9.99962568e-01]
 [  9.99960899e-01   3.91301692e-05]
 [  9.99955535e-01   4.44436046e-05]
 [  3.39294565e-05   9.99966025e-01]
 [  3.50815862e-05   9.99964952e-01]]
Step 500 Loss 3.89266e-05
[1 0 1 0 1 0 1 1 1 1 0 1 1 0 1]
[[  3.88717926e-05   9.99961138e-01]
 [  9.99956250e-01   4.37343697e-05]
 [  3.66972017e-05   9.99963284e-01]
 [  9.99955058e-01   4.49145409e-05]
 [  3.61063794e-05   9.99963880e-01]
 [  9.99954343e-01   4.56960915e-05]
 [  3.26844965e-05   9.99967337e-01]
 [  3.54991607e-05   9.99964476e-01]
 [  3.45580411e-05   9.99965429e

Step 400 Loss 3.71131e-05
[0 1 1 0 1 0 0 1 0 1 1 0 1 1 0]
[[  9.99961257e-01   3.87776017e-05]
 [  3.46519628e-05   9.99965310e-01]
 [  3.65487322e-05   9.99963403e-01]
 [  9.99960661e-01   3.92961629e-05]
 [  3.57539066e-05   9.99964237e-01]
 [  9.99962687e-01   3.73144467e-05]
 [  9.99960423e-01   3.95940078e-05]
 [  3.63319596e-05   9.99963641e-01]
 [  9.99961257e-01   3.87147848e-05]
 [  3.46903798e-05   9.99965310e-01]
 [  3.65324304e-05   9.99963522e-01]
 [  9.99960661e-01   3.93047849e-05]
 [  3.43404281e-05   9.99965668e-01]
 [  3.66835229e-05   9.99963284e-01]
 [  9.99962687e-01   3.72657669e-05]]
Step 500 Loss 3.69462e-05
[0 0 1 1 1 1 0 1 1 0 0 0 1 1 1]
[[  9.99962807e-01   3.71479291e-05]
 [  9.99960542e-01   3.94615126e-05]
 [  3.47586938e-05   9.99965191e-01]
 [  3.48144313e-05   9.99965191e-01]
 [  3.50825576e-05   9.99964952e-01]
 [  3.65208653e-05   9.99963522e-01]
 [  9.99960899e-01   3.90896639e-05]
 [  3.42769235e-05   9.99965668e-01]
 [  3.65583910e-05   9.99963403e

Step 400 Loss 3.53521e-05
[1 1 0 0 0 0 0 1 0 1 1 0 1 1 1]
[[  3.52697389e-05   9.99964714e-01]
 [  3.51213494e-05   9.99964833e-01]
 [  9.99964952e-01   3.50259616e-05]
 [  9.99964595e-01   3.54617441e-05]
 [  9.99964356e-01   3.56868659e-05]
 [  9.99964356e-01   3.55971642e-05]
 [  9.99963880e-01   3.61775201e-05]
 [  3.55989650e-05   9.99964356e-01]
 [  9.99965310e-01   3.47019959e-05]
 [  3.58216166e-05   9.99964118e-01]
 [  3.49221009e-05   9.99965072e-01]
 [  9.99964356e-01   3.56863238e-05]
 [  3.50088594e-05   9.99964952e-01]
 [  3.49951079e-05   9.99964952e-01]
 [  3.53598916e-05   9.99964595e-01]]
Step 500 Loss 3.52361e-05
[1 0 0 1 1 0 0 1 0 1 1 0 1 0 1]
[[  3.54090225e-05   9.99964595e-01]
 [  9.99965906e-01   3.40912338e-05]
 [  9.99963760e-01   3.62742867e-05]
 [  3.52157294e-05   9.99964833e-01]
 [  3.49907023e-05   9.99964952e-01]
 [  9.99965072e-01   3.49194343e-05]
 [  9.99964118e-01   3.59261321e-05]
 [  3.55172451e-05   9.99964476e-01]
 [  9.99965429e-01   3.45764674e

Step 400 Loss 3.36641e-05
[1 1 1 1 1 1 1 1 1 1 1 0 1 0 0]
[[  3.15212928e-05   9.99968529e-01]
 [  3.25323381e-05   9.99967456e-01]
 [  3.24146276e-05   9.99967575e-01]
 [  3.24534194e-05   9.99967575e-01]
 [  3.24390312e-05   9.99967575e-01]
 [  3.24443827e-05   9.99967575e-01]
 [  3.24423418e-05   9.99967575e-01]
 [  3.24431458e-05   9.99967575e-01]
 [  3.24428656e-05   9.99967575e-01]
 [  3.24429602e-05   9.99967575e-01]
 [  3.32993841e-05   9.99966741e-01]
 [  9.99964118e-01   3.58654361e-05]
 [  3.22734522e-05   9.99967694e-01]
 [  9.99964952e-01   3.49903021e-05]
 [  9.99965191e-01   3.48202739e-05]]
Step 500 Loss 3.40885e-05
[0 1 0 1 0 1 1 0 0 0 1 1 1 0 0]
[[  9.99964356e-01   3.56770652e-05]
 [  3.22438937e-05   9.99967813e-01]
 [  9.99964118e-01   3.59036276e-05]
 [  3.20990803e-05   9.99967933e-01]
 [  9.99963999e-01   3.60541162e-05]
 [  3.12347802e-05   9.99968767e-01]
 [  3.33865064e-05   9.99966621e-01]
 [  9.99965429e-01   3.45305343e-05]
 [  9.99965191e-01   3.48658941e

Step 400 Loss 3.27105e-05
[1 1 1 0 0 0 1 1 0 1 1 0 0 0 0]
[[  3.24153407e-05   9.99967575e-01]
 [  3.28022761e-05   9.99967217e-01]
 [  3.13958044e-05   9.99968648e-01]
 [  9.99966264e-01   3.37870042e-05]
 [  9.99966025e-01   3.39773178e-05]
 [  9.99966860e-01   3.31726333e-05]
 [  3.24849352e-05   9.99967456e-01]
 [  3.12136945e-05   9.99968767e-01]
 [  9.99967217e-01   3.27964917e-05]
 [  3.20503204e-05   9.99967933e-01]
 [  3.13647433e-05   9.99968648e-01]
 [  9.99966145e-01   3.38047867e-05]
 [  9.99966025e-01   3.39689250e-05]
 [  9.99965668e-01   3.43330285e-05]
 [  9.99965787e-01   3.41859741e-05]]
Step 500 Loss 3.22766e-05
[1 0 1 1 0 1 1 0 0 1 0 0 0 1 0]
[[  3.13091841e-05   9.99968648e-01]
 [  9.99967456e-01   3.26010377e-05]
 [  3.20216968e-05   9.99967933e-01]
 [  3.12558186e-05   9.99968767e-01]
 [  9.99967337e-01   3.26279405e-05]
 [  3.19998726e-05   9.99968052e-01]
 [  3.12638658e-05   9.99968767e-01]
 [  9.99966264e-01   3.36973535e-05]
 [  9.99967217e-01   3.27921443e

Step 400 Loss 3.17473e-05
[1 0 0 0 0 0 1 0 1 0 0 1 0 0 0]
[[  3.02497447e-05   9.99969721e-01]
 [  9.99966621e-01   3.33431672e-05]
 [  9.99966621e-01   3.33698263e-05]
 [  9.99966145e-01   3.38321406e-05]
 [  9.99966383e-01   3.36432167e-05]
 [  9.99964595e-01   3.54481163e-05]
 [  2.91390206e-05   9.99970913e-01]
 [  9.99964714e-01   3.52983734e-05]
 [  2.85898277e-05   9.99971390e-01]
 [  9.99965668e-01   3.43771972e-05]
 [  9.99965310e-01   3.46330307e-05]
 [  2.93730154e-05   9.99970675e-01]
 [  9.99966621e-01   3.34306969e-05]
 [  9.99966621e-01   3.33193275e-05]
 [  9.99966145e-01   3.38525388e-05]]
Step 500 Loss 3.20159e-05
[1 1 0 0 0 0 1 0 0 0 0 1 0 0 1]
[[  2.69257671e-05   9.99973059e-01]
 [  3.06884394e-05   9.99969363e-01]
 [  9.99967098e-01   3.29101895e-05]
 [  9.99966621e-01   3.34170218e-05]
 [  9.99966383e-01   3.36580451e-05]
 [  9.99964714e-01   3.52474090e-05]
 [  2.91372162e-05   9.99970913e-01]
 [  9.99966502e-01   3.34933684e-05]
 [  9.99966860e-01   3.31332049e

Step 400 Loss 3.05823e-05
[0 0 0 1 0 1 1 0 1 0 1 0 1 0 1]
[[  9.99968290e-01   3.16976075e-05]
 [  9.99968290e-01   3.17252779e-05]
 [  9.99966621e-01   3.33958706e-05]
 [  2.93068715e-05   9.99970675e-01]
 [  9.99967694e-01   3.22693268e-05]
 [  2.72560392e-05   9.99972701e-01]
 [  2.98951691e-05   9.99970078e-01]
 [  9.99967456e-01   3.25299516e-05]
 [  2.91288525e-05   9.99970913e-01]
 [  9.99967575e-01   3.24604771e-05]
 [  2.91692686e-05   9.99970794e-01]
 [  9.99967575e-01   3.24171633e-05]
 [  2.91959295e-05   9.99970794e-01]
 [  9.99967575e-01   3.23884851e-05]
 [  2.92136720e-05   9.99970794e-01]]
Step 500 Loss 3.06474e-05
[0 1 0 0 1 1 1 0 0 0 1 0 0 0 0]
[[  9.99966741e-01   3.32790987e-05]
 [  2.92679069e-05   9.99970675e-01]
 [  9.99969363e-01   3.06390175e-05]
 [  9.99966741e-01   3.32890340e-05]
 [  2.72062061e-05   9.99972820e-01]
 [  2.76846422e-05   9.99972343e-01]
 [  2.98745636e-05   9.99970078e-01]
 [  9.99969125e-01   3.08837043e-05]
 [  9.99968529e-01   3.15068683e

Step 400 Loss 2.91852e-05
[1 1 1 1 0 0 1 1 1 0 1 0 1 1 0]
[[  2.92672921e-05   9.99970675e-01]
 [  2.83989903e-05   9.99971628e-01]
 [  2.91186861e-05   9.99970913e-01]
 [  3.03944435e-05   9.99969602e-01]
 [  9.99972463e-01   2.75846833e-05]
 [  9.99969959e-01   3.00192987e-05]
 [  2.91139095e-05   9.99970913e-01]
 [  2.84647122e-05   9.99971509e-01]
 [  3.06497132e-05   9.99969363e-01]
 [  9.99971271e-01   2.86732411e-05]
 [  3.09770585e-05   9.99969006e-01]
 [  9.99972224e-01   2.77923318e-05]
 [  3.02709850e-05   9.99969721e-01]
 [  2.96071976e-05   9.99970436e-01]
 [  9.99972105e-01   2.79153974e-05]]
Step 500 Loss 2.90262e-05
[0 0 0 1 1 1 0 0 0 0 0 1 1 0 0]
[[  9.99970913e-01   2.90978405e-05]
 [  9.99971628e-01   2.83736226e-05]
 [  9.99970078e-01   2.99011572e-05]
 [  2.90344724e-05   9.99970913e-01]
 [  2.83787103e-05   9.99971628e-01]
 [  3.05513422e-05   9.99969482e-01]
 [  9.99972582e-01   2.74226149e-05]
 [  9.99971271e-01   2.87574785e-05]
 [  9.99971509e-01   2.85029328e

Step 400 Loss 2.81251e-05
[1 1 1 1 1 1 0 0 0 0 0 0 0 1 1]
[[  2.80221375e-05   9.99971986e-01]
 [  2.73870974e-05   9.99972582e-01]
 [  2.80060285e-05   9.99971986e-01]
 [  2.77527342e-05   9.99972224e-01]
 [  2.78520019e-05   9.99972105e-01]
 [  2.93708308e-05   9.99970675e-01]
 [  9.99973297e-01   2.67115483e-05]
 [  9.99972343e-01   2.76317842e-05]
 [  9.99972463e-01   2.75566017e-05]
 [  9.99972463e-01   2.75836574e-05]
 [  9.99972463e-01   2.75727434e-05]
 [  9.99972463e-01   2.75771617e-05]
 [  9.99970794e-01   2.92601235e-05]
 [  2.76608116e-05   9.99972343e-01]
 [  2.91275737e-05   9.99970913e-01]]
Step 500 Loss 2.82299e-05
[0 0 0 1 0 1 0 1 1 0 0 0 1 1 0]
[[  9.99973297e-01   2.67450414e-05]
 [  9.99972463e-01   2.75060083e-05]
 [  9.99970794e-01   2.91949273e-05]
 [  2.90867702e-05   9.99970913e-01]
 [  9.99972224e-01   2.78291973e-05]
 [  2.94732727e-05   9.99970555e-01]
 [  9.99972463e-01   2.75453040e-05]
 [  2.81960820e-05   9.99971747e-01]
 [  2.87806342e-05   9.99971271e

Step 400 Loss 2.71825e-05
[1 1 0 1 1 0 1 1 1 0 0 1 0 1 1]
[[  2.60134839e-05   9.99974012e-01]
 [  2.80611566e-05   9.99971986e-01]
 [  9.99971628e-01   2.84169528e-05]
 [  2.54490951e-05   9.99974608e-01]
 [  2.80161275e-05   9.99971986e-01]
 [  9.99971509e-01   2.84355465e-05]
 [  2.54362112e-05   9.99974608e-01]
 [  2.60904271e-05   9.99973893e-01]
 [  2.80297027e-05   9.99971986e-01]
 [  9.99973536e-01   2.64520695e-05]
 [  9.99970913e-01   2.91098568e-05]
 [  2.74752056e-05   9.99972582e-01]
 [  9.99971867e-01   2.81897392e-05]
 [  2.56038420e-05   9.99974370e-01]
 [  2.60087709e-05   9.99974012e-01]]
Step 500 Loss 2.72684e-05
[0 0 1 0 0 1 0 1 0 0 0 0 0 0 1]
[[  9.99972939e-01   2.70497167e-05]
 [  9.99970913e-01   2.90826647e-05]
 [  2.74011782e-05   9.99972582e-01]
 [  9.99973774e-01   2.61749356e-05]
 [  9.99970913e-01   2.91305187e-05]
 [  2.73736496e-05   9.99972582e-01]
 [  9.99971867e-01   2.81441826e-05]
 [  2.73633923e-05   9.99972582e-01]
 [  9.99973774e-01   2.62054054e

Step 400 Loss 2.63783e-05
[1 1 1 0 1 1 0 0 1 0 1 0 0 1 1]
[[  2.48604792e-05   9.99975085e-01]
 [  2.48619726e-05   9.99975085e-01]
 [  2.66980496e-05   9.99973297e-01]
 [  9.99971867e-01   2.81766224e-05]
 [  2.39312903e-05   9.99976039e-01]
 [  2.68560161e-05   9.99973178e-01]
 [  9.99973774e-01   2.62093308e-05]
 [  9.99971390e-01   2.85689785e-05]
 [  2.60120705e-05   9.99974012e-01]
 [  9.99971986e-01   2.80585882e-05]
 [  2.57220745e-05   9.99974251e-01]
 [  9.99973536e-01   2.64587052e-05]
 [  9.99971509e-01   2.84382586e-05]
 [  2.43015620e-05   9.99975681e-01]
 [  2.48312208e-05   9.99975204e-01]]
Step 500 Loss 2.61764e-05
[1 1 0 1 0 0 1 0 0 1 1 1 1 0 1]
[[  2.48173474e-05   9.99975204e-01]
 [  2.66361785e-05   9.99973416e-01]
 [  9.99971867e-01   2.80934710e-05]
 [  2.56056737e-05   9.99974370e-01]
 [  9.99973536e-01   2.64419305e-05]
 [  9.99971628e-01   2.83286336e-05]
 [  2.60354245e-05   9.99974012e-01]
 [  9.99973893e-01   2.60466477e-05]
 [  9.99971509e-01   2.85232181e

Step 400 Loss 2.55725e-05
[0 1 0 1 1 0 0 0 0 1 0 0 1 0 1]
[[  9.99974132e-01   2.58197651e-05]
 [  2.66857041e-05   9.99973297e-01]
 [  9.99975324e-01   2.46292457e-05]
 [  2.64260234e-05   9.99973536e-01]
 [  2.60561137e-05   9.99973893e-01]
 [  9.99975562e-01   2.44043731e-05]
 [  9.99975204e-01   2.47448424e-05]
 [  9.99975085e-01   2.49149998e-05]
 [  9.99974132e-01   2.58679738e-05]
 [  2.66588177e-05   9.99973297e-01]
 [  9.99976397e-01   2.36044252e-05]
 [  9.99973893e-01   2.61637069e-05]
 [  2.64959999e-05   9.99973536e-01]
 [  9.99975204e-01   2.47636781e-05]
 [  2.62891572e-05   9.99973655e-01]]
Step 500 Loss 2.55534e-05
[0 0 0 1 0 1 0 0 0 0 0 0 1 0 0]
[[  9.99975920e-01   2.40765821e-05]
 [  9.99975204e-01   2.48251126e-05]
 [  9.99974132e-01   2.58362688e-05]
 [  2.65593953e-05   9.99973416e-01]
 [  9.99975324e-01   2.46308900e-05]
 [  2.69666798e-05   9.99973059e-01]
 [  9.99976635e-01   2.33055925e-05]
 [  9.99974728e-01   2.52423106e-05]
 [  9.99975324e-01   2.46321833e

Step 400 Loss 2.48477e-05
[0 1 0 0 0 0 1 1 0 0 0 0 1 0 0]
[[  9.99974370e-01   2.56036237e-05]
 [  2.45738775e-05   9.99975443e-01]
 [  9.99975801e-01   2.42276074e-05]
 [  9.99975443e-01   2.44970124e-05]
 [  9.99975324e-01   2.47220360e-05]
 [  9.99973893e-01   2.60473171e-05]
 [  2.37815020e-05   9.99976277e-01]
 [  2.52242171e-05   9.99974728e-01]
 [  9.99975801e-01   2.42458900e-05]
 [  9.99975562e-01   2.44939092e-05]
 [  9.99975324e-01   2.47233784e-05]
 [  9.99973893e-01   2.60467968e-05]
 [  2.48895649e-05   9.99975085e-01]
 [  9.99976039e-01   2.39621877e-05]
 [  9.99973893e-01   2.60601391e-05]]
Step 500 Loss 2.46824e-05
[0 0 0 1 1 1 0 1 0 0 0 1 1 1 0]
[[  9.99975920e-01   2.41116468e-05]
 [  9.99975562e-01   2.44736657e-05]
 [  9.99973893e-01   2.60632696e-05]
 [  2.36951582e-05   9.99976277e-01]
 [  2.40290537e-05   9.99975920e-01]
 [  2.53257167e-05   9.99974728e-01]
 [  9.99974489e-01   2.55185751e-05]
 [  2.45419815e-05   9.99975443e-01]
 [  9.99975801e-01   2.41492926e

KeyboardInterrupt: 

In [31]:
def prepare_data(x,y,batch_sz,backprop_len,n_epochs):
    nobs = len(x)
    divider = batch_size*backprop_len*n_epochs
    pad_len = divider - (nobs%divider)
    if nobs<pad_len:
        raise Exception("Wrong n_epochs({n_epochs}): choose smaller value.")

    x_batch=np.reshape(
        np.pad(x, (0, pad_len), mode='constant'),
        (n_epochs,batch_sz, -1, backprop_len)
    )
    y_batch=np.reshape(
        np.pad(y, (0, pad_len), mode='constant'),
        (n_epochs,batch_sz, -1, backprop_len)
    )
    n_batches=x_batch.shape[1]
    return x_batch, y_batch, n_batches

In [32]:
xb,yb,n = prepare_data(x,y,batch_size,truncated_backprop_length,100)

In [36]:
x[:50]

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1])

In [34]:
xb[0,:,0,:]

array([[1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1]])

In [35]:
xb[0,:,1,:]

array([[0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0]])

In [28]:
yb[0,1,:,:]

array([[1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1]])

In [15]:
xb2,yb2 = generateData()

In [19]:
print(list(xb2[0]))

[0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 

In [20]:
print(list(yb2[0]))

[0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 

In [68]:
def generateData():
    x = np.array(np.random.choice(2, total_series_length, p=[0.5, 0.5]))
    y = np.roll(x, echo_step)
    y[0:echo_step] = 0

    x = x.reshape((batch_size, -1))
    y = y.reshape((batch_size, -1))

    return (x, y)

In [76]:
echo_step

1

In [69]:
x,y = generateData()

In [75]:
list(zip(x[0].tolist(),y[0].tolist()))

[(0, 0),
 (1, 0),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 0),
 (1, 1),
 (0, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 0),
 (1, 1),
 (0, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (1, 1),
 (0, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (1, 1),
 (0, 1),
 (1, 0),
 (1, 1),
 

array([0, 0, 1, ..., 0, 1, 0])